### ISSUE TITLE
filepicker_image_url doesn't include the handle in the policy

### ISSUE THREAD

**Issue by sguha00** [filestack/filestack-rails#116] opened 2015-01-29 01:56 UTC
When adding the `policy` and `signature` to the image_url, the policy only includes the `call` and `expiry` keys and no `handle` key which is specified here: https://developers.filepicker.io/docs/security/#createPolicy

It seems like the `handle` key is required to read a secure file

**Comment by maurogeorge** [comment] 2015-02-04 21:14
@sguha00 you got any problem? Do you know how to solve it?

This Policy is a thing that I don't know too much, but as you can see here https://github.com/Ink/filepicker-rails/issues/93 I think today this is stable. You can reproduce a error, try to give some examples.

Today the helpers generate url [like this](https://github.com/Ink/filepicker-rails/blob/4218438987a520aaaf8a8a258f5d163a5c4fb870/spec/helpers/application_helper_spec.rb#L260-L284).

Thanks for your feedback

**Comment by maurogeorge** [comment] 2015-06-10 21:50
Closing, since no got any feedback here.

**Comment by danmichaelson** [comment] 2015-12-30 21:10
Can this be re-opened? Looking at the code, we are generating a policy that doesn't specify a file handle. It's valid, but it allows converting any image using the same policy. So if your expiry is 100 years, you aren't adding any security at all as far as I know (because the policy can be grabbed from the URL and reused to convert anything else, forever).

This is maybe not a huge deal now, but it will become important once compatibility is added for converting external URLs (as is supported by the new process.filepicker.io syntax) since then the policy can be hijacked to convert an entirely different set of URLs.

**Comment by maurogeorge** [comment] 2016-01-05 18:50
@danmichaelson I reopen the issue, thanks for the info.

**Comment by danmichaelson** [comment] 2016-01-05 18:55
I emailed Filepicker support about this, they did point out that the current code adds a little bit of security since you at least can't use this policy to _upload_ files. Regardless, specifying the handle is important, especially because a 100-year expiry works much better with CDN's than a 10-minute expiry.

**Comment by dirkkelly** [comment] 2017-02-15 21:05
@danmichaelson @maurogeorge I've opened a Pull Request that adds the handle to secure url generation.

**Closed** 2017-04-06 03:14 UTC
Labels: bug
